version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs
      - nginx-proxy-vhost.d:/etc/nginx/vhost.d
      - nginx-proxy-share:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs
      - nginx-proxy-vhost.d:/etc/nginx/vhost.d
      - nginx-proxy-share:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    links:
      - nginx-proxy

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  nginx-proxy-certs:
  nginx-proxy-vhost.d:
  nginx-proxy-share:
